# Generated by Django 5.1.1 on 2024-09-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='session',
            name='acess_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
