# Generated by Django 5.1.1 on 2024-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sessions', '0011_session_access_slug_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='access_slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Access slug'),
        ),
    ]
