# Generated by Django 5.1.1 on 2024-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sessions', '0012_alter_session_access_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=32, verbose_name='Status'),
        ),
    ]
