# Generated by Django 5.1.1 on 2024-09-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Key')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('config_type', models.CharField(max_length=255, verbose_name='Config type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App settings',
                'indexes': [models.Index(fields=['key'], name='key_index')],
            },
        ),
    ]
