# Generated by Django 5.1.1 on 2024-09-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sessions', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
    ]
