# Generated by Django 5.1.1 on 2024-09-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sessions', '0004_rename_customer_id_session_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='session_id',
            new_name='session',
        ),
    ]
