# Generated by Django 5.1.1 on 2024-09-19 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_alter_customer_created_at_and_more'),
        ('photo_sessions', '0010_session_access_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['access_slug'], name='access_slug_index'),
        ),
    ]
