services:
    photos:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: python manage.py migrate && gunicorn photos.wsgi:application -b :8000 --reload --access-logfile - --error-logfile -
        ports:
            - 8000
        volumes:
            - .:/home/app/photos
            - ./uploads:/home/app/photos/uploads
            - ./static:/home/app/photos/static
            - ./collectstatic:/home/app/photos/collectstatic
        env_file:
            - .env
        restart: always
        depends_on:
            - database
    database:
        image: postgres:15-alpine
        env_file:
            - .env
        volumes:
            - postgresdb:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        restart: always
        expose:
            - 6379
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - photos
