services:
    photos:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py collectstatic --no-input &&
                   gunicorn photos.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 300"
        ports:
            - 8000
        volumes:
            - .:/home/app/photos
            - ./uploads:/home/app/photos/uploads
            - ./static:/home/app/photos/static
            - ./collectstatic:/home/app/photos/collectstatic
        env_file:
            - .env
        restart: always
        depends_on:
            - database
    database:
        image: postgres:15-alpine
        env_file:
            - .env
        volumes:
            - postgresdb:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        restart: always
        expose:
            - 6379

volumes:
    postgresdb:
