# Generated by Django 5.1.1 on 2024-10-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_created_at_alter_package_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='photo_examples', verbose_name='File')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
    ]
