# Generated by Django 5.1.1 on 2024-10-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_section_code_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
