# Generated by Django 5.1.1 on 2024-10-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_sections_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
